name: CI
on:
  schedule:
    - cron: '30 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: npm install
        run: npm install

      - name: load imageData
        run: node index.js

      - name: Commit files
        run: |
          git config --local user.email "answer-3@qq.com"
          git config --local user.name "answer-3"
          git pull
          git add json/*
          git add data/*
          git commit -m "update by github actions"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITTEST }}
          branch: master